[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set up proxy for API requests in production
[[redirects]]
  from = "/api/*"
  to = "https://auto-repair-shop-server.onrender.com/api/:splat"
  status = 200
  force = true
